# Generated by Django 5.0.6 on 2024-07-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_bid_bid_bidvalue_alter_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='currentPrice',
        ),
        migrations.AddField(
            model_name='listing',
            name='startingPrice',
            field=models.FloatField(default=0),
        ),
    ]
